server:
  address: "0.0.0.0"
  port: 52800
  name: "Julian's Strawberry Chat"
  description: "This is Julian's Strawberry Chat instance!"

config:
  max_message_length: 256
  max_users: -1
  max_registered_users: -1
  max_username_length: 32
  max_password_length: 256
  watchdog_timeout: 4

networking:
  ratelimit: true
  ratelimit_timeout: 30

flags:
  enable_messages: true
  enable_queue: true
  debug_mode: false
  online_mode: true
  admins_wait_queue: false
  bots_wait_queue: true

database:
  # Available drivers: mysql
  driver: mysql

  # DB Host & credentials
  host: localhost
  port: 3006
  user: admin
  password: admin

  # Database & table
  database: data
  table: users

security:
  require_signing: false
  signing_key: none
  banned_ips: []


config_ver: 10