name: Question
description: Ask something
labels: [ question ]
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: |
        Ask something, that you want to know, or get help, when you're unsure.
    validations:
      required: true
      
  - type: textarea
    id: other-informations
    attributes:
      label: Other Informations
      description: |
        Other Informations about your question, e.g. spkg version, operating system
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a question
      options:
        - label: |
            This question hasn't been asked. (I have searched my question on GitHub).
          required: true
