proxy: stbm
proxy_version: 2
proxy_mode: full # full, lite, or none
proxy_port: 4020

server_ip: 127.0.0.1 # Change this if needed
server_port: 49200 # Change this if needed
server_requirelogin: True
server_login: username
server_password: password

debug: False # Warning: TLS will get disabled if you set this to True, used for development purposes only
debug_port: 4021
